=== PIP FAQ

==== 隔离模式引起的包依赖不存在问题

提前安装指定版本的 `jmespath`：

[source, bash]
----
pip install 'jmespath>=0.9.3,<1.0.0'
----

`pip install alibaba-cloud-python-sdk-v2` 时，还是提示找不到 `jmespath` 模块：

[source, console]
----
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting alibaba-cloud-python-sdk-v2 (from -r requirements.txt (line 2))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/67/0244b84f93699e67af65bd18d79c090f09cb1af7c2f363586440190dd6c6/alibaba-cloud-python-sdk-v2-1.0.6.tar.gz (793 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 793.4/793.4 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... erroress-exited-with-er
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-800r4u6_/alibaba-cloud-python-sdk-v2_e4a92643a9c349fb8482118c5b1dae7e/setup.py", line 19, in <module>
          VERSION = __import__("alibabacloud").__version__
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-800r4u6_/alibaba-cloud-python-sdk-v2_e4a92643a9c349fb8482118c5b1dae7e/alibabacloud/__init__.py", line 20, in <module>
          from alibabacloud.client import ClientConfig
        File "/tmp/pip-install-800r4u6_/alibaba-cloud-python-sdk-v2_e4a92643a9c349fb8482118c5b1dae7e/alibabacloud/client.py", line 21, in <module>
          import alibabacloud.retry.retry_policy as retry_policy
        File "/tmp/pip-install-800r4u6_/alibaba-cloud-python-sdk-v2_e4a92643a9c349fb8482118c5b1dae7e/alibabacloud/retry/retry_policy.py", line 15, in <module>
          from alibabacloud.retry.retry_condition import *
        File "/tmp/pip-install-800r4u6_/alibaba-cloud-python-sdk-v2_e4a92643a9c349fb8482118c5b1dae7e/alibabacloud/retry/retry_condition.py", line 15, in <module>
          import jmespath
      ModuleNotFoundError: No module named 'jmespath'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
----

确认依赖包的安装和版本无问题后，怀疑 `pip` 运行在虚拟环境或者隔离环境下，不是本机环境：

[source, console]
----
$ pip show jmespath
Name: jmespath
Version: 0.10.0
Summary: JSON Matching Expressions
Home-page: https://github.com/jmespath/jmespath.py
Author: James Saryerwinnie
Author-email: js@jamesls.com
License: MIT
Location: /home/lyuqiang/.local/lib/python3.11/site-packages
Requires: 
Required-by: alibaba-cloud-python-sdk-v2
----

[source, console]
----
$ pip install --help | grep iso
  --no-build-isolation        Disable isolation when building a modern source
  --isolated                  Run pip in an isolated mode, ignoring
----

重新带 `--no-build-isolation` 参数安装解决问题：

[source, bash]
----
pip install --no-build-isolation alibaba-cloud-python-sdk-v2
----

